main: net.dagger.randomitemminigame.LootRushMod
name: LootRush
version: ${version}
description: Мини-игра в которой нужно найти случайный предмет и подставлять противников перед телепортом
authors: [nasarwo]
website:
api-version: 1.26
load: STARTUP

commands:
  lootrush:
    description: Управление мини-игрой
    usage: /lootrush <start|stop|status|role|skip|debug|lang|banlist>
    aliases: [lr]
    permission: lootrush.admin

permissions:
  lootrush.admin:
    description: Позволяет запускать и останавливать мини-игру
    default: op
